version: "3.8"

services:
  db:
    image: postgres:12.5
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    env_file: 
      - ./backend/.env.development
    ports:
      - '5432:5432'
  redisdb:
    image: redis:latest
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'
  meleeme-backend: 
    build: ./backend
    deploy:
      replicas: 1
    env_file: 
      - ./backend/.env.development
    volumes:
      - ./backend:/app
    ports:
      - '4000:4000'
    depends_on: 
      - db
      - redisdb
  meleeme-frontend: 
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'

volumes:
  redisdata: