version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test-app
permissions:
  - object: /
    pattern: "*"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: Scripts/app_stop.sh
  ApplicationStart:
    - location: Scripts/run_app.sh
      timeout: 3600
      runas: ec2-user
  ValidateService:
    - location: Scripts/validate.sh
      timeout: 3600