version: "3.8"

services:
  db:
    image: postgres:12.5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: 
      - ./.env.development
    ports:
      - '5432:5432'
    networks: 
      - meleeme-net
  redisdb:
    image: redis:latest
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'
    networks: 
      - meleeme-net
  meleeme-backend: 
    build: ./
    deploy:
      replicas: 1
    env_file: 
      - ./.env.development
    volumes:
      - ./:/app
    ports:
      - '4000:4000'
    networks: 
      - meleeme-net
    depends_on: 
      - db
      - redisdb

networks:
  meleeme-net:
    driver: bridge
      
volumes:
  redisdata: