version: "3.8"

services:
  db:
    image: postgres:12.5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: 
      - ./.env.development
    ports:
      - '5432:5432'
  redisdb:
    image: redis:latest
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'
  meleeme-backend: 
    build: ./
    deploy:
      replicas: 2
    env_file: 
      - ./.env.development
    volumes:
      - ./:/app
    ports:
      - '4000:4000'
    depends_on: 
      - db
      - redisdb

volumes:
  redisdata: